# SPDX-FileCopyrightText: 2023 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>

check-links:
    #!/usr/bin/env bash
    set -euo pipefail
    make clean
    make
    sed -i.bak -e 's,^baseURL =.*,baseURL = "http://localhost:1313/",' config.toml
    hugo
    mv config.toml.bak config.toml
    python -m http.server 1313 &
    htmltest
    kill %1
