# SPDX-FileCopyrightText: 2025 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
---
DirectoryPath: "public"
IgnoreURLs:
  - "^https://github.com/siemens/wfx.*"
  - "^http://127.0.0.1.*"
  - "^http://localhost.*"
  - "^https://www.mysql.com"
  - "^https://microsoft.com"
  - "^https://www.gnu.org/.*"
  - "^https://www.npmjs.com/"
