all: true
dir: "{{.InterfaceDir}}"
structname: Mock{{.InterfaceName}}
pkgname: "{{ .SrcPackageName }}"
filename: "mock_{{.InterfaceName}}.go"
template: testify
template-data:
  boilerplate-file: .ci/mockery_header.txt
  mock-build-tags: testing
  unroll-variadic: true
packages:
  github.com/siemens/wfx/persistence:
    interfaces:
      Storage: {}
