# SPDX-FileCopyrightText: 2025 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/opensource-nepal/commitlint
    rev: v2.0.0
    hooks:
      - id: commitlint
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 44.54.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.18.0
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: format-go
        name: format Go code
        entry: just _format-go
        language: system
        types: [go]
        pass_filenames: false
      - id: just-fmt
        name: just fmt
        entry: just --fmt --unstable
        language: system
        files: ^justfile$
        pass_filenames: false
      - id: biome
        name: biome check
        entry: biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run --new-from-rev=HEAD
        language: system
        types: [go]
        pass_filenames: false
      - id: staticcheck
        name: staticcheck
        entry: .ci/hooks/staticcheck.sh
        language: system
        types: [go]
