# SPDX-FileCopyrightText: 2023 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
FROM gcr.io/distroless/static-debian11:nonroot@sha256:f41b84cda410b05cc690c2e33d1973a31c6165a2721e2b5343aab50fecb63441

# this file is generated by goreleaser as part of the CI pipeline
COPY wfx /usr/bin/wfx

EXPOSE 8080 8081

ENTRYPOINT ["wfx"]
