# SPDX-FileCopyrightText: 2023 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
FROM gcr.io/distroless/static-debian13:nonroot@sha256:64c43684e6d2b581d1eb362ea47b6a4defee6a9cac5f7ebbda3daa67e8c9b8e6

ARG TARGETPLATFORM

# this file is generated by goreleaser as part of the CI pipeline
COPY $TARGETPLATFORM/wfx /usr/bin/wfx

EXPOSE 8080 8081

ENTRYPOINT ["wfx", "--mgmt-host=0.0.0.0"]
