# SPDX-FileCopyrightText: 2023 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
FROM gcr.io/distroless/static-debian12:nonroot@sha256:730b825b11a473ecb1785c9507c9231dd83db420a1014b0a82decb3d9bc3c75f

# this file is generated by goreleaser as part of the CI pipeline
COPY wfx /usr/bin/wfx

EXPOSE 8080 8081

ENTRYPOINT ["wfx"]
