// SPDX-FileCopyrightText: 2026 Siemens AG
//
// SPDX-License-Identifier: Apache-2.0
//
// Author: Michael Adler <michael.adler@siemens.com>

import { test, expect } from "@playwright/test";
import { cleanupDatabase, createJob, createWorkflow, TEST_TAG } from "./helper";

const baseUrl = "http://localhost:8081";
const uiBaseUrl = baseUrl + "/ui";

// All tests share a single wfx instance. Each test starts and ends by removing
// the resources it created (identified by TEST_TAG), leaving any pre-existing
// data untouched. Assertions are scoped to TEST_TAG for the same reason.
test.beforeEach(async ({ request }) => {
  await cleanupDatabase(baseUrl, request);
});

test.afterEach(async ({ request }) => {
  await cleanupDatabase(baseUrl, request);
});

test("empty jobs table", async ({ page }) => {
  await page.goto(uiBaseUrl);

  // Wait for table to appear
  await page.locator("#jobs-table").waitFor();

  await expect(
    page.locator("#jobs-table> tbody > tr").filter({ hasText: TEST_TAG }),
  ).toHaveCount(0);
});

test("empty workflows table", async ({ page }) => {
  await page.goto(uiBaseUrl);

  const workflowsLink = page.getByRole("link", { name: "Workflows" });
  await workflowsLink.click();

  // Wait for table to appear
  await page.locator("#workflows-table").waitFor();

  await expect(
    page.locator("#workflows-table > tbody > tr").filter({ hasText: TEST_TAG }),
  ).toHaveCount(0);
});

test("non-empty workflows table", async ({ page }) => {
  // Create workflow
  const workflow = await createWorkflow(baseUrl, page.request);
  const name = workflow.name as string;

  await page.goto(uiBaseUrl);

  // Click on "Workflows"
  const workflowsLink = page.getByRole("link", { name: "Workflows" });
  await workflowsLink.click();

  // Wait for table to appear
  await page.locator("#workflows-table").waitFor();

  const matchingRow = page
    .locator("#workflows-table > tbody > tr")
    .filter({ hasText: name });
  await expect(matchingRow).toHaveCount(1);

  await expect(matchingRow.locator("td").first()).toHaveText(name);
});

test("non-empty jobs table", async ({ page }) => {
  // Create workflow
  const workflow = await createWorkflow(baseUrl, page.request);
  const name = workflow.name as string;

  const job = await createJob(baseUrl, page.request, name);
  const jobId = job.id as string;

  await page.goto(uiBaseUrl);

  // Wait for table to appear
  await page.locator("#jobs-table").waitFor();

  const matchingRow = page
    .locator("#jobs-table > tbody > tr")
    .filter({ hasText: jobId });
  await expect(matchingRow).toHaveCount(1);

  await expect(matchingRow.locator("td").first()).toHaveText(jobId);
});

test("job added to jobs table due to server-sent event", async ({ page }) => {
  await page.goto(uiBaseUrl);

  // Wait for table to appear
  await page.locator("#jobs-table").waitFor();
  await expect(
    page.locator("#jobs-table > tbody > tr").filter({ hasText: TEST_TAG }),
  ).toHaveCount(0);

  const workflow = await createWorkflow(baseUrl, page.request);
  const name = workflow.name as string;

  const job = await createJob(baseUrl, page.request, name);
  const jobId = job.id as string;

  // now job should be added to table due to job event sent by wfx
  const matchingRow = page
    .locator("#jobs-table > tbody > tr")
    .filter({ hasText: jobId });
  await expect(matchingRow).toHaveCount(1);

  await expect(matchingRow.locator("td").first()).toHaveText(jobId);
});

test("workflow details", async ({ page }) => {
  // Create workflow
  const workflow = await createWorkflow(baseUrl, page.request);
  const name = workflow.name as string;

  // Open workflow details page
  await page.goto(`${uiBaseUrl}/workflows/${name}`);

  // Check for SVG

  // Wait for <mermaid> to appear
  const mermaid = page.locator("mermaid");
  await mermaid.waitFor();

  // Check <svg> was generated by mermaid
  const svg = mermaid.locator("svg#graphDiv");
  await expect(svg).toBeVisible();

  const classAttr = await svg.getAttribute("class");
  expect(classAttr).toContain("statediagram");

  // Check workflow JSON is highlighted
  const codeBlock = page.locator("code#workflow-json");
  await expect(codeBlock.locator("span.hljs-string").first()).toBeVisible();
});

test("job details", async ({ page }) => {
  const workflow = await createWorkflow(baseUrl, page.request);
  const name = workflow.name as string;

  const job = await createJob(baseUrl, page.request, name);
  const jobId = job.id as string;

  // Open job details page
  await page.goto(`${uiBaseUrl}/jobs/${jobId}`);

  // Check for SVG

  // Wait for <mermaid> to appear
  const mermaid = page.locator("mermaid");
  await mermaid.waitFor();

  // Check <svg> was generated by mermaid
  const svg = mermaid.locator("svg#graphDiv");
  await expect(svg).toBeVisible();

  const classAttr = await svg.getAttribute("class");
  expect(classAttr).toContain("statediagram");

  // Check workflow JSON is highlighted
  const codeBlock = page.locator("code#job-json");
  await expect(codeBlock.locator("span.hljs-string").first()).toBeVisible();

  // Check job details
  const details = page.locator("table#job-details > tbody");
  await expect(
    details.locator('tr:has(td:text("Job ID")) td').nth(1),
  ).toHaveText(jobId);
  await expect(
    details.locator('tr:has(td:text("Client ID")) td').nth(1),
  ).toHaveText("rpi");
  await expect(
    details.locator('tr:has(td:text("State")) td').nth(1),
  ).toHaveText("INSTALL");
  await expect(
    details.locator('tr:has(td:text("Group")) td').nth(1),
  ).toHaveText("OPEN");
  await expect(details.locator('tr:has(td:text("Tags")) td').nth(1)).toHaveText(
    TEST_TAG,
  );
  await expect(
    details.locator('tr:has(td:text("Created")) td').nth(1),
  ).toHaveText(formatDate(new Date(job.stime as string)));
  await expect(
    details.locator('tr:has(td:text("Modified")) td').nth(1),
  ).toHaveText(formatDate(new Date(job.mtime as string)));
});

function formatDate(date: Date): string {
  const pad = (n: number) => n.toString().padStart(2, "0");
  const month = pad(date.getMonth() + 1); // Months are 0-based
  const day = pad(date.getDate());
  const year = date.getFullYear();
  const hours = pad(date.getHours());
  const minutes = pad(date.getMinutes());
  const seconds = pad(date.getSeconds());
  return `${month}/${day}/${year} ${hours}:${minutes}:${seconds}`;
}
