-- create "workflow" table
CREATE TABLE
  "workflow" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying NOT NULL,
    "states" jsonb NOT NULL,
    "transitions" jsonb NOT NULL,
    "groups" jsonb NOT NULL,
    PRIMARY KEY ("id")
  );

-- create index "workflow_name_key" to table: "workflow"
CREATE UNIQUE INDEX "workflow_name_key" ON "workflow" ("name");

-- create "job" table
CREATE TABLE
  "job" (
    "id" character varying NOT NULL,
    "stime" timestamptz NOT NULL,
    "mtime" timestamptz NOT NULL,
    "client_id" character varying NOT NULL,
    "definition" jsonb NULL,
    "status" jsonb NOT NULL,
    "group" character varying NULL,
    "workflow_jobs" bigint NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "job_workflow_jobs" FOREIGN KEY ("workflow_jobs") REFERENCES "workflow" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
  );

-- create index "job_client_id" to table: "job"
CREATE INDEX "job_client_id" ON "job" ("client_id");

-- create index "job_group" to table: "job"
CREATE INDEX "job_group" ON "job" ("group");

-- create index "job_stime" to table: "job"
CREATE INDEX "job_stime" ON "job" ("stime");

-- create "tag" table
CREATE TABLE
  "tag" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying NOT NULL,
    PRIMARY KEY ("id")
  );

-- create index "tag_name" to table: "tag"
CREATE UNIQUE INDEX "tag_name" ON "tag" ("name");

-- create "tag_jobs" table
CREATE TABLE
  "tag_jobs" (
    "tag_id" bigint NOT NULL,
    "job_id" character varying NOT NULL,
    PRIMARY KEY ("tag_id", "job_id"),
    CONSTRAINT "tag_jobs_job_id" FOREIGN KEY ("job_id") REFERENCES "job" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT "tag_jobs_tag_id" FOREIGN KEY ("tag_id") REFERENCES "tag" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
  );

-- create "history" table
CREATE TABLE
  "history" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "mtime" timestamptz NOT NULL,
    "status" jsonb NULL,
    "definition" jsonb NULL,
    "job_history" character varying NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "history_job_history" FOREIGN KEY ("job_history") REFERENCES "job" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
  );

-- added manually, since currently unsupported by entgo
CREATE INDEX idx_status_state ON job ((status ->> 'state'));
