# SPDX-FileCopyrightText: 2024 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
---
name: Chore

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    container: golang:1.22.6@sha256:2bd56f00ff47baf33e64eae7996b65846c7cb5e0a46e0a882ef179fd89654afa
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - run: |
          # find all go.mod files, except in the hugo directory, and run `go mod tidy` inside
          find . -path ./hugo -prune -o -type f -name go.mod -exec dirname {} \; | while read -r dir; do
              cd "$dir"
              go mod tidy
              cd -
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          commit-message: "chore: go mod tidy"
          signoff: true
          branch: chore/go-mod-tidy
          title: "chore: go mod tidy"
