# SPDX-FileCopyrightText: 2024 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
---
name: Chore

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    container: golang:1.23.0@sha256:613a108a4a4b1dfb6923305db791a19d088f77632317cfc3446825c54fb862cd
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - run: |
          # find all go.mod files, except in the hugo directory, and run `go mod tidy` inside
          find . -path ./hugo -prune -o -type f -name go.mod -exec dirname {} \; | while read -r dir; do
              cd "$dir"
              go mod tidy
              cd -
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@4320041ed380b20e97d388d56a7fb4f9b8c20e79 # v7
        with:
          commit-message: "chore: go mod tidy"
          signoff: true
          branch: chore/go-mod-tidy
          title: "chore: go mod tidy"
