# SPDX-FileCopyrightText: 2024 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
---
name: Chore

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    container: golang:1.23.6@sha256:927112936d6b496ed95f55f362cc09da6e3e624ef868814c56d55bd7323e0959
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: |
          # find all go.mod files, except in the hugo directory, and run `go mod tidy` inside
          find . -path ./hugo -prune -o -type f -name go.mod -exec dirname {} \; | while read -r dir; do
              cd "$dir"
              go mod tidy
              cd -
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
        with:
          commit-message: "chore: go mod tidy"
          signoff: true
          branch: chore/go-mod-tidy
          title: "chore: go mod tidy"
