# SPDX-FileCopyrightText: 2023 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
---
name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    needs:
      - ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Download UI artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ui
          path: ui/dist
      - name: Export Golang version as env variable
        run: |
          GO_VERSION=$(sed -n 's/.*container: golang:\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' .github/workflows/ci.yml | head -n1)
          # You can make an environment variable available to any subsequent
          # steps in a workflow job by defining or updating the environment
          # variable and writing this to the GITHUB_ENV environment file.
          echo "GO_VERSION=$GO_VERSION" | tee -a "$GITHUB_ENV"
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Setup Golang caches
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Disable git security features
        run: git config --global safe.directory '*'
      - run: sudo .ci/setup-build.sh

      # even though Windows is not officially supported, we want it to at least compile successfully
      - name: Build for Windows
        run: /usr/bin/env CC=$(pwd)/.ci/zcc goreleaser build --clean --single-target --snapshot
        env:
          GOOS: windows

      - name: Build Snapshot Release for Linux
        run: /usr/bin/env CC=$(pwd)/.ci/zcc goreleaser release --clean --snapshot

      - name: build plugins and contrib
        run: |
          go build -C example/plugin
          go build -C contrib/remote-access/client
          go build -C contrib/config-deployment/client

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: dist
          path: dist/**/*
          retention-days: 5

  test:
    name: Test
    needs:
      - ui
    runs-on: ubuntu-latest
    container: golang:1.26.1@sha256:595c7847cff97c9a9e76f015083c481d26078f961c9c8dca3923132f51fe12f1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Golang caches
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Download UI artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ui
          path: ui/dist
      - run: apt-get update -q && apt-get install -q -y --no-install-recommends zstd
      - run: go generate -tags ui ./ui
      - run: go test -race -coverprofile=coverage1.out -covermode=atomic -timeout 30s --tags=testing,ui ./...
      - run: go test -race -coverprofile=coverage2.out -covermode=atomic -timeout 30s --tags=testing ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage*.out

  test-postgres:
    runs-on: ubuntu-latest
    name: Test PostgreSQL
    container: golang:1.26.1@sha256:595c7847cff97c9a9e76f015083c481d26078f961c9c8dca3923132f51fe12f1
    services:
      postgres:
        image: postgres:18@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
        env:
          # see https://hub.docker.com/_/postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: wfx
          POSTGRES_USER: wfx
          POSTGRES_PASSWORD: secret
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 5s
          --health-retries 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Golang caches
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - run: go test -tags testing,integration,no_mysql -coverprofile=coverage.out -covermode=atomic ./...
        env:
          PGHOST: postgres
          PGPORT: 5432
          PGDATABASE: wfx
          PGUSER: wfx
          PGPASSWORD: secret
          PGSSLMODE: disable
      - name: Upload coverage to Codecov
        # note: v4 is buggy and fails to upload this report
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out

  test-mysql:
    runs-on: ubuntu-latest
    name: Test MySQL
    container: golang:1.26.1@sha256:595c7847cff97c9a9e76f015083c481d26078f961c9c8dca3923132f51fe12f1
    services:
      mysql:
        image: mysql:8-debian@sha256:49f4fcb0087318aa1c222c7e8ceacbb541cdc457c6307d45e6ee4313f4902e33
        env:
          # see https://hub.docker.com/_/mysql
          MYSQL_DATABASE: wfx
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: wfx
          MYSQL_PASSWORD: secret
          MYSQL_HOST: mysql
        # Set health checks to wait until mysql has started
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Golang caches
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - run: go test -tags testing,integration,no_postgres -coverprofile=coverage.out -covermode=atomic ./...
        env:
          MYSQL_DATABASE: wfx
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: wfx
          MYSQL_PASSWORD: secret
          MYSQL_HOST: mysql
      - name: Upload coverage to Codecov
        # note: v4 is buggy and fails to upload this report
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out

  cli-tests:
    name: CLI Tests
    runs-on: ubuntu-latest
    container: golang:1.26.1@sha256:595c7847cff97c9a9e76f015083c481d26078f961c9c8dca3923132f51fe12f1
    services:
      mysql:
        image: mysql:8-debian@sha256:49f4fcb0087318aa1c222c7e8ceacbb541cdc457c6307d45e6ee4313f4902e33
        env:
          # see https://hub.docker.com/_/mysql
          MYSQL_DATABASE: wfx
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: wfx
          MYSQL_PASSWORD: secret
          MYSQL_HOST: mysql
        # Set health checks to wait until mysql has started
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 20
      postgres:
        image: postgres:18@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
        env:
          # see https://hub.docker.com/_/postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: wfx
          POSTGRES_USER: wfx
          POSTGRES_PASSWORD: secret
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 5s
          --health-retries 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: "true"
      - name: Setup Golang caches
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - run: .ci/setup-cli-tests.sh
      - name: Disable git security features
        run: git config --global safe.directory '*'
      - name: install wfx
        run: go install .
      - name: install wfxctl
        run: go install ./cmd/wfxctl
      - name: build plugins
        run: go build -C example/plugin
      - name: run tests
        env:
          PGHOST: postgres
          PGPORT: 5432
          PGUSER: wfx
          PGPASSWORD: secret
          PGDATABASE: wfx
          MYSQL_DATABASE: wfx
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: wfx
          MYSQL_PASSWORD: secret
          MYSQL_HOST: mysql
        working-directory: test
        run: export PATH=$(go env GOPATH)/bin:$PATH; bats .

  lint:
    needs: [ui]
    runs-on: ubuntu-latest
    name: Lint
    container: golang:1.26.1@sha256:595c7847cff97c9a9e76f015083c481d26078f961c9c8dca3923132f51fe12f1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Download UI artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ui
          path: ui/dist
      - run: .ci/setup-lint.sh
      - run: go generate -tags ui ./ui
      - name: Disable git security features
        run: git config --global safe.directory '*'
      - run: just lint

  format:
    runs-on: ubuntu-latest
    name: Format
    container: golang:1.26.1@sha256:595c7847cff97c9a9e76f015083c481d26078f961c9c8dca3923132f51fe12f1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: lts/*
      - run: .ci/setup-format.sh
      - run: just format
      - name: Disable git security features
        run: git config --global safe.directory '*'
      - run: git diff --exit-code

  reuse:
    runs-on: ubuntu-latest
    name: Reuse
    container: fsfe/reuse:6.2.0@sha256:85462a75c0f8efda09ddd190b92816b70e7662577c8427429e11e1b9f25a992e
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: reuse lint || true # just a warning

  generate:
    name: Generate Code
    runs-on: ubuntu-latest
    container: golang:1.26.1@sha256:595c7847cff97c9a9e76f015083c481d26078f961c9c8dca3923132f51fe12f1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install packages
        run: .ci/setup-generate.sh
      - name: Disable git security features
        run: git config --global safe.directory '*'
      - run: just generate
      - run: git diff --exit-code

  openapi-check-breaking:
    name: API check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Check for breaking changes in API
        id: breaking_changes
        uses: oasdiff/oasdiff-action/breaking@1f38ea5ea0b4a2e4e49901c3bcdf4386a05e9ea1 # v0.0.37
        with:
          base: https://raw.githubusercontent.com/siemens/wfx/refs/heads/main/spec/wfx.openapi.yml
          revision: spec/wfx.openapi.yml
          fail-on: ERR

  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: |
          GLEAM_VERSION=$(grep -oP 'GLEAM_VERSION=\K[0-9.]+' .ci/packages/versions.env)
          REBAR3_VERSION=$(grep -oP 'REBAR3_VERSION=\K[0-9.]+' .ci/packages/versions.env)
          OTP_VERSION=$(grep -oP 'OTP_VERSION=\K[0-9.]+' .ci/packages/versions.env)
          echo "GLEAM_VERSION=$GLEAM_VERSION" | tee -a "$GITHUB_ENV"
          echo "REBAR3_VERSION=$REBAR3_VERSION" | tee -a "$GITHUB_ENV"
          echo "OTP_VERSION=$OTP_VERSION" | tee -a "$GITHUB_ENV"
      - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1
        with:
          gleam-version: "${{ env.GLEAM_VERSION }}"
          rebar3-version: "${{ env.REBAR3_VERSION }}"
          otp-version: "${{ env.OTP_VERSION }}"
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: lts/*
      - run: sudo .ci/setup-ui.sh
      - name: Install deps
        run: |
          npm ci
          gleam deps download
        working-directory: ui
      - name: Test
        run: gleam test
        working-directory: ui
      - name: Format
        run: gleam format --check src test
        working-directory: ui
      - name: Build
        run: just build
        working-directory: ui
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: ui
          path: |
            ui/dist/*
          retention-days: 1

  test-ui:
    name: Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs:
      - build
      - ui
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Download UI artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ui
          path: ui/dist
      - name: Download wfx
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: dist
          path: dist
      # upload-artifact does not retain permissions, see https://github.com/actions/upload-artifact/issues/38
      - name: Make 'wfx' binary globally available
        run: install -v -D -m0755 dist/wfx-with-ui_linux_amd64_v1/wfx /usr/local/bin/wfx

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
        working-directory: ui/integration
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ui/integration
      - name: Run Playwright tests
        run: npx playwright test --project chromium --project firefox --project webkit
        working-directory: ui/integration
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1

  release:
    name: Release
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    needs:
      - build
      - test
      - test-postgres
      - test-mysql
      - format
      - cli-tests
      - lint
      - reuse
      - generate
      - openapi-check-breaking
      - ui
      - test-ui
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download UI artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ui
          path: ui/dist/
      - name: Export Golang version as env variable
        run: |
          GO_VERSION=$(sed -n 's/.*container: golang:\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' .github/workflows/ci.yml | head -n1)
          # You can make an environment variable available to any subsequent
          # steps in a workflow job by defining or updating the environment
          # variable and writing this to the GITHUB_ENV environment file.
          echo "GO_VERSION=$GO_VERSION" | tee -a "$GITHUB_ENV"
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Setup build
        run: sudo .ci/setup-build.sh
      - name: Run GoReleaser
        run: export CC="$(pwd)/.ci/zcc"; goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
