# SPDX-FileCopyrightText: 2026 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
---
name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - name: Login to GitHub Container Registry
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup-ui

      - name: Generate SBOM for ui/
        id: ort
        uses: oss-review-toolkit/ort-ci-github-action@086d928d24ef1653dc0777296b312fda5faaaf52 # v1.2.0
        with:
          image: ghcr.io/oss-review-toolkit/ort-minimal:latest@sha256:8da0e190af68d710cbf469c22ed1912b2c32cfff0f5de1ff5a87a189de1cfbd0
          project-path: ${{ github.workspace }}/ui
          run: >-
            cache-dependencies,
            analyzer,
            reporter
          report-formats: "CycloneDx"
          ort-cli-report-args: "-O CycloneDX=output.file.formats=json"
      - name: Copy SBOM into ui/
        run: cp "${{ steps.ort.outputs.results-sbom-cyclonedx-json-path }}" ui/ui.cyclonedx.sbom.json

      - name: Export Golang version as env variable
        run: |
          GO_VERSION=$(sed -n 's/.*container: golang:\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' .github/workflows/ci.yml | head -n1)
          echo "GO_VERSION=$GO_VERSION" | tee -a "$GITHUB_ENV"
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Setup build
        run: sudo .ci/setup-build.sh
      - name: Run GoReleaser
        run: |
          export CC="$(pwd)/.ci/zcc"
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            goreleaser release --clean
          else
            goreleaser release --clean --snapshot --skip=publish,sign
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshot dist
        if: "!startsWith(github.event.ref, 'refs/tags/v')"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: dist-snapshot
          path: dist/
          retention-days: 1

      - name: Upload snapshot SBOM
        if: "!startsWith(github.event.ref, 'refs/tags/v')"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: sbom-snapshot
          path: ui/*.cyclonedx.sbom.json
          retention-days: 1
